{
    "name": "Gestión de Reportes",
    "version": "1.0",
    "category": "Inventory",
    "summary": "Reportes dinámicos Detalles Textiles",
    "author": "Detalles Textiles",
    "depends": ["stock", "product", "sale", "point_of_sale", "pos_sunat_direct", "web"],
    "data": [
        "views/stock_quant_filters.xml",
        "views/product_stock_filters.xml",
        "views/stock_move_filters.xml",
        "views/stock_analysis_filters.xml",
        "views/pos_commercial_report_views.xml",
        "views/pos_order_filters.xml",
        "views/stock_picking_print_button.xml",
        "views/pos_order_list_inherit.xml",
        "views/dashboard_tiendas_views.xml",
        "report/external_layout_dt.xml",
        "report/paperformat.xml",
        "report/stock_quant_template.xml",
        "report/stock_quant_report.xml",
        "report/product_stock_template.xml",
        "report/product_stock_report.xml",
        "report/stock_move_line_template.xml",
        "report/stock_move_line_report.xml",
        "report/internal_transfer_report.xml",
        "report/internal_transfer_template.xml",
        "report/internal_transfer_ticket_html.xml",
        "report/stock_analysis_report.xml",
        "report/stock_analysis_template.xml",
        "report/pos_commercial_template.xml",
        "report/pos_commercial_report.xml",
        "data/server_action.xml",
        "data/pos_order_excel_action.xml",
        "views/reporte_movimientos_prendas_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "dt_gestion_reportes/static/src/js/dashboard_tiendas.js",
            "dt_gestion_reportes/static/src/xml/dashboard_tiendas.xml",
        ],
        "point_of_sale._assets_pos": [
            "dt_gestion_reportes/static/src/js/reporte_movimientos_prendas_pos.js",
            "dt_gestion_reportes/static/src/xml/reporte_movimientos_prendas_pos.xml",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
